#!/usr/bin/env bash

set -e
set -o pipefail

echo "|> install go 1.21"

# Install Go 1.21
GO_VERSION=1.21
GO_TAR=go$GO_VERSION.linux-amd64.tar.gz
GO_URL=https://go.dev/dl/$GO_TAR

echo "|> downloading Go $GO_VERSION"
curl -LO $GO_URL
sudo tar -C /usr/local -xzf $GO_TAR
rm $GO_TAR

# Set up Go environment variables
export PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/ubuntu/go
export PATH=$PATH:$GOPATH/bin

# Verify Go installation
go version

echo "|> install static asset tool"
go install github.com/mjibson/esc@latest

echo "|> install Elm tooling"
npm install -g elm
npm install -g elm-test

echo "|> install sysconf"
cd /home/ubuntu
if [ ! -d sysconfcpus/bin ]; then
    git clone https://github.com/obmarg/libsysconfcpus.git
    cd libsysconfcpus
    ./configure --prefix=/home/ubuntu/sysconfcpus
    make && make install
fi

echo "|> install Elm packages"
cd /home/ubuntu/snaas/cmd/console/tests
elm-package install -y

echo "|> prepare directories"
mkdir -p /home/ubuntu/.go_workspace/src/github.com/tapglue
rm -rf /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
cp -R /home/ubuntu/snaas /home/ubuntu/.go_workspace/src/github.com/tapglue/

echo "|> install Go packages"
cd /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
go mod download
