#!/usr/bin/env bash

set -e
set -o pipefail

echo "|> prepare env"
export CWD=$(pwd)

echo "|> execute Go tests"
go test \
	-v \
	-race \
	./core/...

go test \
	-v \
	-race \
	./handler/...

go test \
	-v \
	-race \
	./platform/...

go test \
	-v \
	-race \
	-tags integration \
	./service/... \
	--postgres.url="postgres://ubuntu:unicode@127.0.0.1/circle_test?sslmode=disable"
